### ISSUE TITLE
# of images in repo truncated to 1000?

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/made-mistakes-images#1]
Does this mean we won't see all images?
<img width="752" alt="screen shot 2016-04-16 at 3 27 15 am" src="https://cloud.githubusercontent.com/assets/300046/14580201/38cfd252-0383-11e6-9199-d27a82a0a24a.png">

**Comment by mmistakes** [comment]
Probably. To be honest I don't think this is an issue or something I care about. I'm not exactly browsing my images on GitHub :wink:
